export const STATUS = {
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
  NONE: 'NONE',
};

export const GET_LIST_USER_STATUS = {
  SUCCESS: 'GET_LIST_USER_SUCCESS',
  FAIL: 'GET_LIST_USER_FAIL',
  NONE: 'NONE',
};
